version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app-php
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/html/app
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation_salles
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
